---
layout: default
tags: [ manuscript, ]
---

Sequential versions of the manuscript in PDF format as well as checklist for revision to Nature Communications.

The checklist can be found [here]({{ site.baseurl}}/assets/projects/monoallelic-brain/nat-comms-checklist.csv).

Recent versions of the manuscript are listed in reverse chronological order and can be downloaded via the links.

1. as of 2018-04-27, before final resubmission
    * [manuscript pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-04-27-monoall-ms.pdf)
    * [supplementary information pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-04-27-supplementary-information.pdf)
1. as of 2018-03-19, before resubmission
    * [manuscript pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-19-monoall-ms.pdf)
    * [manuscript pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-19-manuscript-changes.pdf) with changes highlighted
    * [supplementary information pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-19-supplementary-information.pdf)
    * [supplementary information pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-19-supplementary-information-changes.pdf) with changes highlighted
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-14-monoall-ms.pdf) as of 2018-03-14
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-03-06-monoall-ms.pdf) as of 2018-03-06
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2018-02-01-monoall-ms.pdf) as of 2018-02-01
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-12-12-monoall-ms.pdf) as of 2017-12-12
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-11-17-monoall-ms.pdf) as of 2017-11-17
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-10-30-monoall-ms.pdf) as of 2017-10-30
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-10-27-b-monoall-ms.pdf) as of 2017-10-27 evening
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-10-27-monoall-ms.pdf) as of 2017-10-27 afternoon
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-10-16-monoall-ms.pdf) as of 2017-10-16
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-08-30-monoall-ms.pdf) as of 2017-08-30; Main text word count:
   1. allowed: 1500
   1. counted by atp-latex: 1466
   1. counted by LibreOffice Writer: 1476
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-08-23-monoall-ms.pdf) as of 2017-08-23
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-08-10-monoall-ms.pdf) as of 2017-08-10
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-30-monoall-ms.pdf) as of 2017-07-30
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-28-monoall-ms.pdf) as of 2017-07-28 with parts deleted
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-26-monoall-ms.pdf) as of 2017-07-26
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-24-monoall-ms.pdf) as of 2017-07-24
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-19-monoall-ms.pdf) as of 2017-07-19 with parts deleted
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-07-18-monoall-ms.pdf) as of 2017-07-18 with parts marked up for change
1. [pdf]({{ site.baseurl }}/assets/projects/monoallelic-brain/2017-02-10-monoall-ms.pdf) as of 2017-02-10
