## Prepare data

```{r message=FALSE, warning=FALSE}
library(lattice)
library(latticeExtra)
library(ggplot2)
library(GGally)
source("../../src/import-data.R")
source("../../src/fit-glms.R")
```

```{r cache=TRUE, echo=FALSE}
E <- get.predictors()
Y <- get.readcounts(gene.ids) # gene.ids is predifined
# e.vars defined in fit-glms.R
S.long <- reshape(cbind(lapply(Y, getElement, "S"), E[ e.vars ]), # the data to be reshaped; e.vars is predifined
                  v.names = "S", varying = list(names(Y)), # the component that varies with genes ('time')
                  timevar = "Gene", times = names(Y), # the 'time' variable, i.e. gene symbol
                  ids = rownames(E), idvar = "sample.id", # observation names: RNA sample ids
                  direction = "long")
S.long$Gene <- factor(S.long$Gene, levels = names(Y), ordered = TRUE)
# in what follows exclude the unweighted averages 'UA.8' and 'UA' because total read count 'N' is not available for those
Y.long <- cbind(stack(lapply(Y[ c(gene.ids, "WA.8", "WA") ], getElement, "S")),
                stack(lapply(Y[ c(gene.ids, "WA.8", "WA") ], getElement, "N")),
                E[ rep(seq_len(nrow(E)), length(gene.ids) + 2), e.vars ])
names(Y.long)[1:3] <- c("S", "Gene", "N")
Y.long$Gene <- factor(Y.long$Gene, levels = names(Y)[ 0:1 - length(Y) ], ordered = TRUE)
Y.long[[4]] <- NULL
```

## Dependence of $S$ on certain variables

### Dependence on gene, age, and institution

Implementation of the same plot both with the `lattice` and the `ggplot2` package.
```{r S-age-smooth, dev=c("png", "pdf"), fig.width=10, cache=TRUE, warning=FALSE}
lattice.options(default.args = list(as.table = TRUE))
P <- list()
# lattice implementation
P$s.age.inst$lattice <-
    xyplot(S ~ Age | Gene, data = S.long, groups = Institution,
           panel = function(x, y, ...) {
               panel.xyplot(x, y, pch = "o", ...)
               panel.smoother(x, y, col = "black", lwd = 2, ...)
           },
           auto.key = list(title = "Insitution", space = "right"),
           aspect = "fill", layout = c(6, 5))
# ggplot2 implementation
g <- ggplot(data = S.long, aes(x = Age, y = S))
g <- g + geom_point(pch = "o", aes(color = Institution))
g <- g + geom_smooth(method = "loess", color = "black")
g <- g + facet_wrap(~ Gene)
P$s.age.inst$ggplot2 <- g
plot(P$s.age.inst$lattice)
plot(P$s.age.inst$ggplot2)
```

### Dependence on gene, age, and total read count $N$

It is unclear how to best implement the `ggplot2` figure below using the `lattice` package.
```{r S-age-tot-read-count, dev=c("png", "pdf"), fig.width=10, cache=TRUE, warning=FALSE, echo=FALSE}
g <- ggplot(Y.long, aes(x = Age, y = S, color = log10(N)))
g <- g + geom_point(alpha = I(0.2))
g <- g + scale_color_gradient(low = "blue", high = "red")
g <- g + facet_wrap(~ Gene)
P$s.age.n$ggplot2 <- g
plot(P$s.age.n$ggplot2)
```

```{r cache=TRUE}
M <- do.all.fits(Y[ 0:1 - length(Y) ], # omit the last two components: "UA.8" and "UA"
                 E, preds = e.vars, sel.models = c("wnlm.R", "logi.S"),
                 x = TRUE, y = TRUE) # store model matrix 'x' and response 'y'
```

## Associations between explanatory variables

```{r rin-rin2, dev=c("png", "pdf"), fig.width=5, cache=TRUE, warning=FALSE, echo=FALSE}
xyplot(RIN2 ~ RIN, data = E[sort.int(E$RIN, index.return = TRUE)$ix, ],
       type = "l", grid = TRUE, aspect = 1)
qplot(RIN, RIN2, data = E[sort.int(E$RIN, index.return = TRUE)$ix, ],
      geom = "line", asp = 1)
```

```{r evar-scatterplot-matrix, dev=c("png", "pdf"), fig.width=10, fig.asp=1, cache=TRUE, warning=FALSE, echo=FALSE, message=FALSE}
P$splom$lattice <-
    splom(E[ e.vars[c(1:6, 10)]], pch = "o", alpha = 0.3, xlab = "", pscales=0,
          panel = function(x, y, ...)
              panel.splom(x, y, ..., jitter.x = ! is.numeric(x), jitter.y = ! is.numeric(y))
          )
#P$splom$ggplot2 <- ggpairs(E[ e.vars[c(1:6, 10)]])
plot(P$splom$lattice)
#plot(P$splom$ggplot2)
ggpairs(E[ e.vars[c(1:6, 10)]])
```
