get.coef <- function(batch = "Gene", model = M5, fun = ranef, reverse = TRUE, prettify = TRUE) {
    df <- fun(model)[[batch]]
    lv <-
        if (reverse) rev(rownames(df))
    else rownames(df)
    f <- factor(rownames(df), levels = lv, ordered = TRUE)
    df <- stack(df)
    df[["batch.levels"]] <- f
    df[["batch"]] <- batch
    pretty.batch <- function(batch.levels, batch.name = "Gene", interceptAs1 = TRUE) {
        x <- gsub("^.*\\(([^)]+)\\).*$", paste0("\\(\\1\\|", batch.name, "\\)"), batch.levels)
        if (interceptAs1) return(gsub("Intercept", "1", x))
        else return(x)
    }
    if (prettify)
        df$ind <- factor(pretty.batch(df$ind, batch), levels = pretty.batch(levels(df$ind), batch))
    return(df)
}


# subtract reference level 1 from levels 2, 3,... of 'values' in a data frame
# that is generated by get.coef
#
# Arguments
# cf: a data frame of coefficients and related information, generated by get.coef
# e.var: the explanatory variable whose levels we want to subtract from its reference level
# df: additional data frame containing the observations on each variable
#
# Value: a list of data frames of the same structure as 'cf' corresponding to levels 2, 3,... 
contrast.coef <- function(cf = get.coef("Gender:Gene"), e.var = "Gender", df = dat) {
    helper <- function(y) {
        x <- cf[grep(y, cf$batch.levels), ]
        x$batch.levels <- gsub(y, "", x$batch.levels)
        x$batch.levels <- gsub(":", "", x$batch.levels)
        x$batch <- gsub(e.var, "", x$batch)
        x$batch <- gsub(":", "", x$batch)
        return(x)
    }
    l <- lapply(lv <- levels(df[[e.var]]), helper)
    names(l) <- lv
    lapply(l[-1],
           function(x) {
               v <- x$value - l[[1]]$value
               cbind(data.frame(values = v), l[[1]][-1])
           })
}

mydotplot <- function(x = get.coef(), ...) {
    n <- names(x)
    fo <- as.formula(paste0("`", n[3], "`", " ~ `", n[1], "` | `", n[2], "`"))
    dotplot(fo, data = x, scales = list(x = list(relation = "free")),
            main = expression(paste("Predicted random coefficient ", b[jg], ".  Mixed model unlm.Q")),
            xlab = "",
            ...)
}
