## Data preparation

```{r echo=FALSE}
library(lattice)
library(latticeExtra)
opts_chunk$set(dpi = 144)
opts_chunk$set(out.width = "700px")
opts_chunk$set(dev = c("png", "pdf"))
lattice.options(default.args = list(as.table = TRUE))
#lattice.options(default.theme = "col.whitebg")
lattice.options(default.theme = "standard.theme")
lattice.options(default.args = list(as.table = TRUE))
```

Load data importer functions:
```{r}
source("../../src/import-data.R")
source("../../src/fit-glms.R")
source("2016-08-23-glm-sampling-distributions.R")
```

Do the import:

```{r cache=TRUE}
genes2fit <- unlist(read.csv("../../data/genes.regression.new", as.is = TRUE))
names(genes2fit) <- genes2fit
E <- get.predictors() # default arguments
Y <- get.readcounts(gene.ids = genes2fit, count.thrs = 0)
```

Fit models:

```{r cache=TRUE, warning=FALSE}
# exclude unweighed aggregates UA.8 and UA from fitting
ids2fit <- grep("^UA(.8)?$", names(Y), value = TRUE, invert = TRUE)
M <- list()
f.ids <- list()
M$multi <- do.all.fits(Y[ids2fit], preds = e.vars)
f.ids$multi <- as.data.frame(lapply(M$multi, function(m) ! sapply(m, is.null)))
f.ids$multi["TMEM261P1", c("logi.S", "logi2.S")] <- FALSE
f.ids$multi[c("WA.8", "WA"), ] <- FALSE # gene aggregates are not needed here
M$simple <- do.all.fits(Y[ids2fit], preds = "Age")
f.ids$simple <- as.data.frame(lapply(M$simple, function(m) ! sapply(m, is.null)))
f.ids$simple["TMEM261P1", c("logi.S", "logi2.S")] <- FALSE
f.ids$simple[c("WA.8", "WA"), ] <- FALSE # gene aggregates are not needed here
```

## Results

```{r cache=TRUE}
plots <- list()
plots$GRB10 <- plot.mdls.1gene(gene = "GRB10", l.l.M = M$simple) 
plots$PEG3 <- plot.mdls.1gene(gene = "PEG3", l.l.M = M$simple) 
```

```{r GRB10, echo=FALSE}
print(plots$GRB10$logi.S, split = c(1, 1, 2, 2), more = TRUE)
print(plots$GRB10$logi.S.large, split = c(2, 1, 2, 2), more = TRUE)
print(plots$GRB10$wnlm.S, split = c(1, 2, 2, 2), more = TRUE)
print(plots$GRB10$wnlm.R, split = c(2, 2, 2, 2), more = FALSE)
```

```{r PEG3, echo=FALSE}
print(plots$PEG3$logi.S, split = c(1, 1, 2, 2), more = TRUE)
print(plots$PEG3$logi.S.large, split = c(2, 1, 2, 2), more = TRUE)
print(plots$PEG3$wnlm.S, split = c(1, 2, 2, 2), more = TRUE)
print(plots$PEG3$wnlm.R, split = c(2, 2, 2, 2), more = FALSE)
```
