```{r echo=FALSE}
library(ggplot2)
library(lattice)
opts_chunk$set(dpi = 144)
opts_chunk$set(out.width = "700px")
opts_chunk$set(dev = c("png", "pdf"))
lattice.options(default.args = list(as.table = TRUE))
lattice.options(default.theme = "standard.theme")
```

Load functions

```{r}
source("~/projects/monoallelic-brain/src/import-data.R")
source("~/projects/monoallelic-brain/src/fit-glms.R")
```

```{r}
gene.ids <- unlist(read.csv("../../data/genes.regression.new", as.is = TRUE))
names(gene.ids) <- gene.ids
```

Get data
```{r cache=TRUE, warning=FALSE}
E <- get.predictors() # default arguments
Y <- get.readcounts(gene.ids = gene.ids, count.thrs = 0)
```

Import outliers of the CMC study provided by Mette and Jessica and check if any has been included in our previous analyses.  The answer is: they have all been excluded.

```{r}
read.csv("../../data/outliers.csv", colClasses = "character")$DissectionID %in% row.names(E)
```

Fit logi.S and wnlm.R models

```{r cache=TRUE, warning=FALSE, message=FALSE}
# exclude unweighed aggregates UA.8 and UA from fitting
to.fit.ids <- grep("^UA(.8)?$", names(Y), value = TRUE, invert = TRUE)
sel.models <- c("logi.S", "wnlm.R"); names(sel.models) <- sel.models
M <- do.all.fits(Y[to.fit.ids], G = E, preds = e.vars, sel.models = sel.models)
```

