### Preparations

```{r echo=FALSE, warnings=FALSE}
library(ggplot2)
library(lattice)
library(latticeExtra)
opts_chunk$set(dpi = 144)
opts_chunk$set(out.width = "700px")
opts_chunk$set(dev = c("png", "pdf"))
lattice.options(default.args = list(as.table = TRUE))
lattice.options(default.theme = "standard.theme")
```

Load functions

```{r}
source("~/projects/monoallelic-brain/src/import-data.R")
source("~/projects/monoallelic-brain/src/fit-glms.R")
source("~/projects/monoallelic-brain/src/graphics.R")
```

```{r}
gene.ids <- unlist(read.csv("../../data/genes.regression.new", as.is = TRUE))
names(gene.ids) <- gene.ids
names(e.vars) <- e.vars
```

```{r cache=TRUE, warning=FALSE}
E <- get.predictors() # default arguments
Y <- get.readcounts(gene.ids = gene.ids, count.thrs = 0)
```

```{r cache=TRUE, warning=FALSE, message=FALSE}
set.seed(1976)
perms <- data.frame(cbind(seq_len(nrow(E)), replicate(n.perm <- 1e3, sample.int(nrow(E)))))
names(perms) <- c("U", paste0("P", seq_len(n.perm)))
sel.models <- c("wnlm.Q")
sel.vars <- e.vars[c(1, 3, 5, 8)]
system.time(Betas <- aggregate.CI.permut2(perms = perms, gene.ids = gene.ids, e.vars = e.vars,
                                          sel.vars = sel.vars, sel.models = sel.models,
                                          E = E, Y = Y[gene.ids], skip.CI = TRUE))
```

The expressions above obtain the null distribution of regression coefficients for the selected predictor(s) `r sel.vars` under the selected model(s) `r sel.models` based on `r n.perm` permutations.

```{r beta-age-null-wnlm-Q}
beta0densityplot("Age")
```

```{r beta-gender-null-wnlm-Q}
beta0densityplot("GenderMale")
```

```{r beta-dx-scz-wnlm-Q}
beta0densityplot("DxSCZ")
```

```{r beta-dx-aff-wnlm-Q}
beta0densityplot("DxAFF")
```

```{r beta-ancestry-1-null-wnlm-Q}
beta0densityplot("Ancestry.1")
```
