#! /bin/sh

gene="ANGEL1"
nastr="NA"

# convert to asciidoc format with long lines
pandoc -f html -t asciidoc --columns=1000 |
# extract the table from the entire document
sed -ne '/^|=\+$/, /^|=\+$/ p' |
# delete uninformative rows, then put all SNP-related data on separate line(s)
sed -ne "1 d; 3 d; $ d; s/\<ND\>/${nastr}/g; \
    /^|${gene}/ s/^\(\(|[^|]*\)\(|[^|]*\)\(|[^|]*\)\{10\}\)\(.*\)$/\1\n\3\n\5/; p" \
    > ${gene}.tmp
# create not SNP-specific data table
# 1. remove first column (the name of the gene)
sed -ne "/^\(|\s*${gene}\s*|\)\(.*\)$/ {s//\2/; p}" ${gene}.tmp |
# 2. duplicate NA values for the L,H column
sed -e "/^\(\([^|]*|\)\{6\}\)\(\s*${nastr}\s*|\)\(.*\)$/ \
    s//\1${nastr},${nastr} |\4/; \
    s/\s*|\s*/,/g" 
#tr ' ' '_'
#tr -d '\n' | tr '\a' '\n'
