#! /bin/bash

gene=$1
html="$gene/$gene.html" 
nastr="NA"
tmp=$(mktemp)
nsnps=4

# convert to asciidoc format with long lines
pandoc -f html -t asciidoc --columns=1000 $html |

sed -e "
    # delete rows above and below table
    0,/^|=\+$/ d
    /^|=\+$/, $ d
    # replace 'ND's by the R friendly 'nastr'
    s/\<ND\>/${nastr}/g
    # duplicate ${nastr} values for the L,H column
    /^\(\(|[^|]*\)\{7\}\)\(|\s*${nastr}\s*\)\(.*\)$/ s//\1|${nastr},${nastr}\4/
    # mark the start of each future row with an '\a'
    /^|\(${gene}\s*|\([^|]*|\)\{11\}\)\(.*\)$/ s//\a\1\a\3/
" |
tr -d '\n*' | tr '\a' '\n' |
sed -e "
    1 d; 4 d; 5 d
" |
sed -e "
    4~2 { s/| \+|/|NA,NA,NA|/g
    s/\s*+\([[:digit:].]\+\)|\([[:digit:].]\+\)|\([[:digit:].]\+\)\s*|/,\1,\2,\3|/g
    s/\s*+[^[:digit:]]\+|/,NA,NA,NA|/g
    s/\([[:digit:]]\+\)-\([[:digit:]]\+\(,[[:digit:].NA]\+\)\{3\}\)/\1,\2/g
    s/\(\([[:digit:].NA]\+,\)\{4\}\([[:digit:].NA]\+\)\)|/\1,/g
    }
"
