#! /bin/sh

# Prepares two csv files to be imported to R, which contain data on predictors
# (a.k.a. explanatory variables or covariates).

# input: files from Ifat
#indir="$HOME/projects/monoallelic-brain/data/ifat/age-dependence"
inpred=$1
#inpred="$indir/DLPFC.ensembl.KNOWN_AND_SVA.ADJUST.SAMPLE_COVARIATES.tsv"
samples=$2
#samples="$indir/samples.csv"

# output: two csv files prepared for import to R
outdir=$3
#outdir="$HOME/projects/monoallelic-brain/data/predictors"
if [ ! -d $outdir ]
then mkdir $outdir
fi
# mapping between RNAseqID (present in read count tables) and DLPFC_RNA_ID (present in the table of predictors)
outid="$outdir/RNAseq_ID.DLPFC_RNA_ID.csv"
# table of predictors
outpred="$outdir/predictors.csv"

# extract the RNAseq_ID and DLPFC_RNA_ID columns
tr '\r' '\n' < $samples | cut -d ',' -f '3,19' > $outid
# convert tabs to commas and simplify column names (of predictors)
tr '\t' ',' < $inpred | \
    sed -e '
    1 {
    s/DLPFC_RNA_isolation: Sample RNA ID/DLPFC_RNA_ID/
    s/Age of Death/Age/
    s/PMI (in hours)/PMI/
    s/DLPFC_RNA_isolation: RIN/RIN/
    s/DLPFC_RNA_isolation: RIN\^2/RIN2/
    s/DLPFC_RNA_report: Clustered Library Batch/RNA_batch/
    s/Ancestry.EV/Ancestry/g
    s/\s\+/_/g
    }
    ' > $outpred
