#! /bin/sh

# Create a csv formatted table to STDOUT from an input summary html documents
# presented by http://katahdin.mssm.edu/ifat/web/cm/get_pop_freq.pl Especially
# from summary-all-genes.html

if [ $# != 1 ]
then
cat 2>&1 <<EOF
usage: $(basename $0) input.html
EOF
exit 1
fi

# input and temporary files
inhtml=$1
tmp1=$(mktemp)
tmp2=$(mktemp)

# convert to plain text file
pandoc -f html -t plain \
   +RTS -K64M -RTS $inhtml | # increase memory to prevent stack space overflow
# extract table
sed -n '/^Symbol/, $ p' |
# delete every second row (empty) and mark every 36th with an \a
sed '2~2 d; 37~36 s/^/\a/' |
# turn 1 column table into a 36 column csv
tr '\n\a' ',\n' |
# change 'ND's to 'NA', the default na.string in R
# remove the string 'chr' from chromosome numbers
# remove trailing commas
# and write to tmp1
sed '$ d
    s/,ND,/,NA,/g
    s/chr\([[:digit:]]\+\)/\1/
    s/,$//
' > $tmp1
# copy header at line 1 to tmp2
sed '1 q' $tmp1 > $tmp2
# remove headers at any lines (there should be two, one at line 1 and another
# near the bottom of the table)
sed '/^Symbol/ d' $tmp1 >> $tmp2
cat $tmp2
rm $tmp1 $tmp2
